# Generated by Django 5.1.1 on 2024-10-17 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookStoreApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='bookstore',
            name='id',
        ),
        migrations.AlterField(
            model_name='bookstore',
            name='slug',
            field=models.SlugField(default='', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bookstore',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookStoreApp.author'),
        ),
    ]
