# Generated by Django 5.1.1 on 2024-10-17 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookStoreApp', '0002_author_remove_bookstore_id_alter_bookstore_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=30)),
                ('postal_code', models.IntegerField()),
                ('city', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='BookStoreApp.address'),
        ),
    ]
