# Generated by Django 5.1.1 on 2024-10-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookStoreApp', '0003_address_author_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=3)),
            ],
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Address Entries'},
        ),
        migrations.AddField(
            model_name='bookstore',
            name='countries',
            field=models.ManyToManyField(related_name='bookstore', to='BookStoreApp.countries'),
        ),
    ]
